### ISSUE TITLE
Dynamic top bar

### ISSUE THREAD

**Issue by therealbenhogan** [pineconellc/angular-foundation#179] opened 2015-01-13 13:31 UTC
Hi, 

I'm trying to make the topbar directive dynamic - please see http://plnkr.co/edit/xoQ0i8UMq3JNUK8aMaYq?p=preview

Issues are that the dropdowns dont display on hover and if you collapse the menu down on a smaller screen and then go back to a wider screen, the menu items collapse on each other.

Any help much appreciated!

**Comment by circlingthesun** [comment] 2015-01-13 13:44
I had a quick look. I'm not exactly sure what the problem is, however, your directives are generating markup which will likely not produce html compatible with the foundation css. What happens is instead of getting ```<ul></ul>``` you are getting ```<my-directive><ul></ul></my-directive>```. What you can try do is set ```replace: true``` inside your directives. This will remove the directive markup around your templates. You do however need to make sure your templates have a single root. Also note that ```replace: true``` is marked as deprecated in the angular docs. As far as I know it still works though.

**Comment by therealbenhogan** [comment] 2015-01-13 14:52
Hi,
Thanks for getting back. That's definitely an issue - I've tried using replace (as you say, don't like doing that as it's being deprecated), but that doesnt help anyway. Tried also using a <div> with a class name for the directive but that didnt work either ! There's probably a better way to create the directives to overcome the CSS issue?

**Comment by circlingthesun** [comment] 2015-01-13 15:00
I have some code that does what you want. It's not great but hopefully it'll help you achieve what you want. http://pastebin.com/08PHEeSC

**Comment by circlingthesun** [comment] 2015-01-13 15:07
The directive above converts the structure below into menu markup:

```
var menu = [
    {
        'text': 'Calendar',
        'icon': 'fa-book ',
        'url': '/'
    },
    {
        'text': 'Clients',
        'icon': 'fa-users ',
        'url': '/clients'
    },
    {
        'text': 'Settings',
        'icon': 'fa-gears',
        'submenu': [
            {
                'text': 'Calendar',
                'icon': 'fa-book ',
                'url': '/'
            },
            {
                'text': 'Clients',
                'icon': 'fa-users ',
                'url': '/clients'
            },
        ]
    },
    {
        'text': 'Share',
        'icon': 'fa-share-alt ',
        'url': '/share'
    }
]

```

**Comment by therealbenhogan** [comment] 2015-01-13 15:08
Many thanks - I'll take a look asap and get back to you!

**Comment by therealbenhogan** [comment] 2015-01-14 07:23
Sorry for the late reply - this is very useful - many thanks for sharing!

**Comment by circlingthesun** [comment] 2015-01-14 13:07
:+1:

**Closed** 2015-01-14 14:19 UTC
