### ISSUE TITLE
How to get rid of the delay between modal and fog disapearance with angular-foundation?

### ISSUE THREAD

**Issue by limax84** [pineconellc/angular-foundation#203] opened 2015-03-16 22:47 UTC
I'm using the JS lib **angular-foundation** for my modals.

The problem is that when I close the modal, there is a short delay between the modal's and the background fog's disapearances. It seems very unpleasant for the eye of the user.

It's the simpliest case for **$modal**, out of the box. So, is this a bug? How could I customize this behaviour?
(Ideally using css transitions :)

Here is my **index.html** :

    <!doctype html>
    <html ng-app="modalApp">
    <head>
      <link href="http://cdnjs.cloudflare.com/ajax/libs/foundation/5.2.0/css/foundation.css" rel="stylesheet">
      <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.3/angular.js"></script>
      <script src="http://pineconellc.github.io/angular-foundation/mm-foundation-tpls-0.5.1.js"></script>
      <script src="sample.js"></script>
    </head>
    <body ng-controller="mainCtrl">
      <script type="text/ng-template" id="modalContent.html">
        <div>
          <h3>I'm a modal</h3>
          <button class="button" ng-click="ok()">OK</button>
        </div>
      </script>
      <button class="button" ng-click="open()">Open me</button>
    </body>
    </html>

and here is my **sample.js** :

    angular.module('modalApp', ['mm.foundation']);
    angular.module('modalApp').controller('mainCtrl', function($scope, $modal) {
      $scope.open = function() {
        $modal.open({
          templateUrl: 'modalContent.html',
          controller: 'modalCtrl'
        });
      };
    });
    angular.module('modalApp').controller('modalCtrl', function($scope, $modalInstance) {
      $scope.ok = function() {
        $modalInstance.close();
      };
    });

You can run this code in this [Plunker][1].

Any ideas?

Thanks

  [1]: http://plnkr.co/edit/X7RS02gTrUqOjtASKPSK?p=preview

**Comment by jbrowning** [comment] 2015-03-16 23:20
It is common for modal windows to animate when opening and closing. To support this, the `$modalStack` service waits 300ms before removing the modal backdrop. Currently there's no way to disable this behavior. To override, you'll either need to fork the project and remove the delay or submit a PR which allows for configuration.

**Comment by limax84** [comment] 2015-03-17 09:27
Hey, thanks for the answer.

I found it in the code, actually it's 300ms before the modal removal and 150ms between modal and backdrop removals.
You say that this delays exist to support animations' times. But this forced sequentiality :

-> modal closing animation (300ms)
-> modal removal
-> backdrop disaprearance animation (150ms)
-> backdrop removal

does not allow for very esthetic behaviours, and even when tunning the transitions ([Plunker][1]), the closing action will always be at least 300ms long, which is not acceptable for a lot of professional use cases.

What do you mean by "submit a PR" ?

  [1]: http://plnkr.co/edit/X7RS02gTrUqOjtASKPSK?p=preview

**Comment by jbrowning** [comment] 2015-03-17 12:29
This delay is a relic from [Angular Bootstrap](https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L190-L208) upon which our project is based. For the time being, this delay is acceptable in our own application so we do not have the time or resources to make this configurable ourselves. If you would like to contribute such a feature, I'd be happy to accept a _Pull Request_.

**Comment by limax84** [comment] 2015-03-17 12:37
Cool, I'll think about it.
Thanks for your time.

**Closed** 2015-04-06 12:58 UTC

**Comment by jeremyhewett** [comment] 2015-10-08 22:29
The problem is not the delay itself, but rather that the animation that is supposed to happen during that delay is broken. This can be seen on angular-foundation's own plunker: http://plnkr.co/edit/RIsBM1uGbYMwUVTzNtN3?p=preview

The modal does not animate in or out. It shows instantly with no animation, and then closes in two ugly steps with no animation.
